// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"api/adapter"
	"api/adapter/repo"
	"api/adapter/rest/handler"
	"api/usecase"
)

// Injectors from wire.go:

func InitializeMailHandler(db adapter.Database) handler.Mail {
	mail := repo.NewMail(db)
	usecaseMail := usecase.NewMail(mail)
	handlerMail := handler.NewMail(usecaseMail)
	return handlerMail
}
